name: Auto build for windows

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
          go-version: '1.18'
          check-latest: true
    - uses: actions/checkout@v3

    - name: Package Application
      run: go build

    - name: download WinDivert.dll
      run: |
        Invoke-WebRequest -v -o ./WinDivert.zip https://github.com/basil00/Divert/releases/download/v2.2.2/WinDivert-2.2.2-A.zip
        Expand-Archive ./WinDivert.zip -DestinationPath ./
        mv WinDivert-2.2.2-A/x86_64/WinDivert.dll ./

    - name: get config
      run: mv ./release/* ./

    - uses: actions/upload-artifact@v3
      with:
        name: hmoepioneer
        path: |
          hmoepioneer.exe
          default.conf
          startup.bat
          WinDivert.dll
          WinDivert64.sys
